#!/bin/sh
# borrowed from the venerable tpope:
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

# exit as soon as something fails
set -e

# remove tags if exiting unexpected, such as due to the above "set -e"
trap "rm -f .git/tags.$$" EXIT

# generate tags in a temporary file
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git

# move the new tags over the previous tags (atomic-ish?)
mv .git/tags.$$ .git/tags
