#!/bin/sh
echo "* Disabling wifi... "

if ps ax|awk '{print$5}'|grep 'wpa_supplicant' >/dev/null; then
	echo -n " - Killing wpa_supplicant... "
	if pkill wpa_supplicant; then
		echo "done."
	else
		echo "FAILED!"
		exit 1
	fi
fi
if ps ax|awk '{print$5}'|grep 'dhclient' >/dev/null; then
	echo -n " - Killing dhclient... "
	if pkill dhclient; then
		echo "done."
	else
		echo "FAILED!"
		exit 1
	fi
fi

echo -n " - Bringing down wlan0..."
ifconfig wlan0 down 2>/dev/null
echo "done."

if [ "$(uname -n)" = "am" ] && lsmod | grep -q "iwlwifi"
then
	echo -n " - Removing wireless drivers"
	rmmod iwlvm
	rmmod iwldvm
	rmmod iwlwifi
	echo "done."
fi

echo "+ Disabled."
