#!/bin/sh
export PATH="/usr/bin"
cd /
#exec /bedrock/cross/bin/sudo -u web /bedrock/cross/bin/firefox "${@}"
exec /bedrock/cross/bin/sudo -u web /bedrock/strata/debian/usr/local/bin/dbus-firefox "${@}"
