#!/bin/sh

winid=""
winname=""
initwinid=""
populate_wininfo() {
	initwinid="$(xdotool getactivewindow)"
	rootid="$(xdotool search --maxdepth 0 --name "")" 2>/dev/null
	winid="$(xdotool search --name "$1" | grep -v "^$rootid$" | head -n1)"
	[ -n "$winid" ] && winname="$(xdotool getwindowname "$winid")"
}

run_in_window() {
	eval $(xdotool getmouselocation --shell)
	xdotool mousemove --window "$initwinid" 0 0
	xdotool mousemove --window "$winid" 0 0
	eval "$@"
	xdotool mousemove --window "$winid" 0 0
	xdotool mousemove --window "$initwinid" 0 0
	xdotool mousemove "$X" "$Y"
}

if ps -e -o comm | grep -q '^mpd$'
then
	mpc next
elif ps -e -o comm | grep -q '^mocp$'
then
	nocmp --next
elif ps -e -o comm | grep -q '^pianobar$'
then
	echo n > ~/.config/pianobar/ctl
elif populate_wininfo "mpv - "
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers ">" && sleep 0.1'
elif populate_wininfo "VLC media player"
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers "n" && sleep 0.1'
elif populate_wininfo "Netflix"
then
	# skip intro
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers "S" && sleep 0.1'
elif populate_wininfo "Twitch"
then
	false
elif populate_wininfo " . Prime Video"
then
	false
elif populate_wininfo "YouTube"
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers "N" && sleep 0.1'
fi
