#!/bin/sh

winid=""
winname=""
initwinid=""
populate_wininfo() {
	initwinid="$(xdotool getactivewindow)"
	rootid="$(xdotool search --maxdepth 0 --name "")" 2>/dev/null
	winid="$(xdotool search --name "$1" | grep -v "^$rootid$" | head -n1)"
	[ -n "$winid" ] && winname="$(xdotool getwindowname "$winid")"
}

run_in_window() {
	eval $(xdotool getmouselocation --shell)
	xdotool mousemove --window "$initwinid" 0 0
	xdotool mousemove --window "$winid" 0 0
	eval "$@"
	xdotool mousemove --window "$winid" 0 0
	xdotool mousemove --window "$initwinid" 0 0
	xdotool mousemove "$X" "$Y"
}

if ps -e -o comm | grep -q '^mpd$' && [ "$(mpc | wc -l)" -gt 1 ]
then
	mpc toggle
elif ps -e -o comm | grep -q '^mocp$'
then
	mocp --toggle-pause
elif ps -e -o comm | grep -q '^pianobar$'
then
	echo p > ~/.config/pianobar/ctl
elif populate_wininfo "mpv - "
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers " " && sleep 0.1'
elif populate_wininfo "VLC media player"
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers " " && sleep 0.1'
elif populate_wininfo "Netflix"
then
	# Space is inconsistent due to UI element focus concerns
	# Clicking in top-left corner hits Firefox chrome.  Click just slightly down.
	run_in_window 'sleep 0.1 \
		&& xdotool mousemove --window "$winid" "1" "50" \
		&& xdotool click --clearmodifiers 1 \
		&& sleep 0.1'
elif populate_wininfo "Twitch"
then
	# assumes fullscreen
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers " " && sleep 0.1'
elif populate_wininfo " . Prime Video"
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers " " && sleep 0.1'
elif populate_wininfo "YouTube"
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers " " && sleep 0.1'
fi
