#!/bin/sh

winid=""
winname=""
initwinid=""
populate_wininfo() {
	initwinid="$(xdotool getactivewindow)"
	rootid="$(xdotool search --maxdepth 0 --name "")" 2>/dev/null
	winid="$(xdotool search --name "$1" | grep -v "^$rootid$" | head -n1)"
	[ -n "$winid" ] && winname="$(xdotool getwindowname "$winid")"
}

run_in_window() {
	xdotool mousemove --window "$initwinid" 0 0
	xdotool mousemove --window "$winid" 0 0
	eval "$@"
	xdotool mousemove --window "$winid" 0 0
	xdotool mousemove --window "$initwinid" 0 0
}

if ps -e -o comm | grep -q '^mpd$'
then
	ncmpcpp toggle
elif ps -e -o comm | grep -q '^mocp$'
then
	mocp --toggle-pause
elif ps -e -o comm | grep -q '^pianobar$'
then
	echo p > ~/.config/pianobar/ctl
elif populate_wininfo "mpv - "
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers " "'
elif populate_wininfo "VLC media player"
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers " "'
elif populate_wininfo "YouTube"
then
	window_width=$(xdotool getwindowgeometry "$winid" | awk '$1 == "Geometry:" {print$2}' | cut -dx -f1)
	cursor_x_pos=$(expr $window_width / 2 - 100)
	run_in_window 'xdotool mousemove --window "$winid" "$cursor_x_pos" 100 && xdotool click --clearmodifiers 1'
elif populate_wininfo "Netflix"
then
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers " "'
elif populate_wininfo "Twitch"
then
	# assumes fullscreen
	run_in_window 'sleep 0.1 && xdotool type --clearmodifiers " "'
fi
