#!/bin/sh

winid=""
winname=""
initwinid=""
populate_wininfo() {
	initwinid="$(xdotool getactivewindow)"
	rootid="$(xdotool search --maxdepth 0 --name "")" 2>/dev/null
	winid="$(xdotool search --name "$1" | grep -v "^$rootid$" | head -n1)"
	[ -n "$winid" ] && winname="$(xdotool getwindowname "$winid")"
}

run_in_window() {
	eval $(xdotool getmouselocation --shell)
	xdotool mousemove --window "$initwinid" 0 0
	xdotool mousemove --window "$winid" 0 0
	eval "$@"
	xdotool mousemove --window "$winid" 0 0
	xdotool mousemove --window "$initwinid" 0 0
	xdotool mousemove "$X" "$Y"
}

if ps -e -o comm | grep -q '^mpd$'
then
	mpc status | head -n1
elif ps -e -o comm | grep -q '^mocp$'
then
	if mocp --format "%title" | grep -q '.'
	then
		mocp --format "%title"
	else
		mocp --format "%file"
	fi
elif ps -e -o comm | grep -q '^pianobar$'
then
	awk 'BEGIN{RS=".\x1B[[]2K";ORS="\n"}/^\|>  /{x=substr($0,5)}END{print x}' ~/.config/pianobar/out
elif populate_wininfo " - mpv"
then
	echo "$winname" | sed 's/ - mpv$//'
elif populate_wininfo "VLC media player"
then
	echo "$winname" | sed 's/ - VLC media player.*$//'
elif populate_wininfo "Netflix"
then
	echo "Netflix"
elif populate_wininfo "Twitch"
then
	echo "$winname" | sed 's/ - Twitch.*$//'
elif populate_wininfo " . Prime Video"
then
	echo "$winname" | sed -e 's/^Watch //' -e 's/ . Prime Video.*$//'
elif populate_wininfo "YouTube"
then
	echo "$winname" | sed 's/ - YouTube.*$//'
fi
