#!/bin/sh

winid=""
winname=""
initwinid=""
populate_wininfo() {
	initwinid="$(xdotool getactivewindow)"
	rootid="$(xdotool search --maxdepth 0 --name "")" 2>/dev/null
	winid="$(xdotool search --name "$1" | grep -v "^$rootid$" | head -n1)"
	[ -n "$winid" ] && winname="$(xdotool getwindowname "$winid")"
}

run_in_window() {
	xdotool mousemove --window "$initwinid" 0 0
	xdotool mousemove --window "$winid" 0 0
	eval "$@"
	xdotool mousemove --window "$winid" 0 0
	xdotool mousemove --window "$initwinid" 0 0
}

if ps -e -o comm | grep -q '^mpd$'
then
	false
elif ps -e -o comm | grep -q '^mocp$'
then
	false
elif ps -e -o comm | grep -q '^pianobar$'
then
	sed 's/\r......../\n/g' ~/.config/pianobar/out | grep '^"' | tail -n1
elif populate_wininfo "mpv - "
then
	echo "$winname" | sed 's/^mpv - //'
elif populate_wininfo "VLC media player"
then
	echo "$winname" | sed 's/ - VLC media player.*$//'
elif populate_wininfo "YouTube"
then
	echo "$winname" | sed 's/ - YouTube.*$//'
elif populate_wininfo "Netflix"
then
	false
fi
