#!/bin/sh
# wrapper for steam to fix minor annoyances

# use alsa for sound
export SDL_AUDIODRIVER=ALSA

if [ "$(uname -n)" = "am" ]
then
	export MESA_EXTENSION_OVERRIDE='GL_EXT_texture_filter_anisotropic'
fi

sv down xcape
steam

# restore cursor
xsetroot -cursor_name left_ptr

rm /dev/shm/org.chromium.Chromium.shmem.libcef_*
rm /dev/shm/$(whoami)-Shm_*
rm /dev/shm/$(whoami)-ValveIPCSharedObjects*

sv up xcape
