#!/bin/sh
# wrapper for steam to fix minor annoyances

## use alsa for sound
#export SDL_AUDIODRIVER=ALSA

# fix locale
#export LOCALE=C

# fix supreme commander
#export PROTON_NO_ESYNC=1

# fix for intel graphics
if [ "$(uname -n)" = "am" ]
then
	export MESA_EXTENSION_OVERRIDE='GL_EXT_texture_filter_anisotropic'
fi

# disable xcape in games
init_xcape_status="$(conctl s xcape | awk -F'[ ,]' '{print$5}')"
conctl d xcape

strat -r ubuntu /usr/games/steam

# restore cursor
xsetroot -cursor_name left_ptr

# restore xcape
conctl "${init_xcape_status}" xcape

# remove steam-created temp files
rm -f /dev/shm/u$(id -u)-Shm_*
rm -f /dev/shm/u$(id -u)-Valve*
