#!/bin/sh
# wrapper for steam to fix minor annoyances

# use alsa for sound
export SDL_AUDIODRIVER=ALSA

# locale fix
export LOCALE=C

if [ "$(uname -n)" = "am" ]
then
	export MESA_EXTENSION_OVERRIDE='GL_EXT_texture_filter_anisotropic'
fi

init_xcape_status="$(conctl s xcape | awk -F'[ ,]' '{print$5}')"
conctl d xcape
steam

# restore cursor
xsetroot -cursor_name left_ptr

rm /dev/shm/org.chromium.Chromium.shmem.libcef_*
rm /dev/shm/$(whoami)-Shm_*
rm /dev/shm/$(whoami)-ValveIPCSharedObjects*

conctl "$init_xcape_status" xcape
