#!/bin/sh

# disable xcape in games
init_xcape_status="$(conctl s xcape | awk -F'[ ,]' '{print$5}')"
conctl d xcape

/bedrock/cross/bin/sudo -u games /bedrock/strata/debian/usr/local/bin/steam-wrap

# restore cursor
xsetroot -cursor_name left_ptr

# restore xcape
conctl "${init_xcape_status}" xcape
