#!/bin/sh
# wrapper for steam to fix minor annoyances

cd /

# max memory limit in kilobytes
ulimit -m "$(expr 1024 \* 1024 \* 12)"
# virtual limit in kilobytes
ulimit -v "$(expr 1024 \* 1024 \* 12)"

## use alsa for sound
#export SDL_AUDIODRIVER=ALSA

# fix locale
#export LOCALE=C

# fix supreme commander
#export PROTON_NO_ESYNC=1

# fix for intel graphics
if [ "$(uname -n)" = "am" ]
then
	export MESA_EXTENSION_OVERRIDE='GL_EXT_texture_filter_anisotropic'
fi

# disable xcape in games
init_xcape_status="$(conctl s xcape | awk -F'[ ,]' '{print$5}')"
conctl d xcape

# restrict
export PATH="/home/paradigm/.go/bin:/home/paradigm/.priv:/home/paradigm/.bin:/bedrock/cross/pin/bin:/bedrock/bin:/usr/local/bin:/usr/local/sbin:/opt/bin:/opt/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/snap/bin:/bedrock/cross/bin"

/bedrock/cross/bin/sudo -u "$(whoami)-steam" /bedrock/cross/bin/steam "${@}"

# restore cursor
xsetroot -cursor_name left_ptr

# restore xcape
conctl "${init_xcape_status}" xcape

# remove steam-created temp files
rm -f /dev/shm/u$(id -u)-Shm_*
rm -f /dev/shm/u$(id -u)-Valve*
