#!/bin/sh
# Wrapper for timew that removes a single tag to the currently tracked tag set

if [ -z "$1" ]
then
	echo "No tag provided"
	exit 1
fi

if timew stop >/dev/null 2>&1
then
	# split the current
	timew continue >/dev/null 2>&1
	timew untag @1 $@
	# probably unnecessary given how close stop/continue will be
	timew lengthen @2 :fill >/dev/null 2>&1
fi

# if there are no tags, stop
if timew | head -n1 | grep -q "^Tracking *$"
then
	timew stop >/dev/null 2>&1
	timew delete @1 >/dev/null 2>&1
fi

timew
