#!/bin/sh
# Wrapper for timew that removes a single tag to the currently tracked tag set

if [ -z "$1" ]
then
	echo "No tag provided"
	exit 1
fi

if echo "$1" | grep -q "['\"\\]"
then
	echo "Quote detected specified tag, aborting"
	exit 1
fi

if timew | grep -q '^There is no'
then
	echo "ERROR: Tag not found"
	exit 1
fi

if timew export | jq -r 'map(select(has("end") == false))[0].tags[]' | grep -q "['\"\\]"
then
	echo "Quote detected in tag set, aborting"
	exit 1
fi

found=false
IFS="
"
for tag in $(timew export | jq -r 'map(select(has("end") == false))[0].tags[]')
do
	if [ "$tag" = "$1" ]
	then
		found=true
	fi
done


if ! "$found"
then
	echo "ERROR: Specified tag not in tag set"
	exit 1
fi

if [ "$(timew export | jq -r 'map(select(has("end") == false))[0].tags | length')" -eq 1 ]
then
	echo "\$ timew stop"
	timew stop
	pkill -HUP dwmstatus
	exit 0
fi


echo "\$ timew start $(timew export | jq -c 'map(select(has("end") == false))[0].tags | map(select(.!= "'"$1"'"))[]' | tr '\n' ' ')"
sh -c "timew start $(timew export | jq -c 'map(select(has("end") == false))[0].tags | map(select(.!= "'"$1"'"))[]' | tr '\n' ' ')"
pkill -HUP dwmstatus
