#!/bin/sh

if [ "$1" = "-a" ]
then
	while ! wifion; do true; done
	exit $?
fi

echo "* Connecting to the internet... "

if [ "$(uname -n)" = "am" ] && ! lsmod | grep -q "^iwlwifi$"
then
	echo -n " - Loading wireless drivers"
	modprobe iwldvm
	modprobe iwlwifi
	echo "done."
fi

if ps ax|awk '{print$5}'|grep -q 'wpa_supplicant'
then
	echo -n " - Killing previous wpa_supplicant... "
	if pkill wpa_supplicant; then
		echo "done."
	else
		echo "FAILED!"
		exit 1
	fi
fi
if ps ax|awk '{print$5}'|grep -q 'dhclient'
then
	echo -n " - Killing previous dhclient... "
	if pkill dhclient; then
		echo "done."
	else
		echo "FAILED!"
		exit 1
	fi
fi

echo -n " - Bringing up wireless interface... "
sleep 1s
WIRELESS_DEVICE=$(iwconfig 2>/dev/nulll | awk '/^w/{print$1;exit}')
echo "USING: $WIRELESS_DEVICE"
ifconfig $WIRELESS_DEVICE up
echo "done."

echo -n " - Enabling power saving... "
iwconfig $WIRELESS_DEVICE power on
echo "done."

echo -n " - Detecting which SSID to connect to... "
SSIDS="$(ls /etc/wpa_supplicant/ | grep 'wpa_supplicant\.conf' | cut -c21-)"
IFS="
"
for POSSIBLE_SSID in $SSIDS; do
	if iwlist $WIRELESS_DEVICE scanning | grep "^\s*ESSID:\"$POSSIBLE_SSID\"" 1>/dev/null; then
		SSID=$POSSIBLE_SSID
	fi
done
if [ -z $SSID ]; then
	echo "\nNo recognized network found, aborting."
	return 1
else
	echo $SSID
fi

echo -n " - Starting wpa_supplicant... "
if [ -e /etc/wpa_supplicant/wpa_supplicant.log ]; then
	rm /etc/wpa_supplicant/wpa_supplicant.log
	touch /etc/wpa_supplicant/wpa_supplicant.log
fi
wpa_supplicant -Dwext -i$WIRELESS_DEVICE -c/etc/wpa_supplicant/wpa_supplicant.conf-$SSID -B -f/etc/wpa_supplicant/wpa_supplicant.log
echo "done."

START_TIME=$(date +%s)
echo -n " - Waiting for association with access point"
while ! grep 'Associated with [0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]' 1>/dev/null /etc/wpa_supplicant/wpa_supplicant.log && [ "$(expr $(date +%s) - $START_TIME)" -lt 10 ]; do
	echo -n "."
	sleep .2s
done
echo " done."

if ! grep 'Associated with [0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]' 1>/dev/null /etc/wpa_supplicant/wpa_supplicant.log
then
	echo "Could not connect to WPA, aborting"
	exit 1
fi

echo -n " - Getting IP address..."
if dhclient $WIRELESS_DEVICE $1
then
	echo "done."
else
	echo "FAILED!"
	exit 1
fi

echo -n " - Testing network connection..."
if ping -c 1 www.example.com 1>/dev/null; then
	echo "done."
else
	echo "FAILED!"
	exit 1
fi
echo "+ Connected."
