#!/data/data/com.termux/files/usr/bin/sh
~/.bin/conctl s sshd
echo "vvv"
if  [ $(~/.bin/conctl --state sshd) = "up" ]
then
	~/.bin/conctl d sshd
else
	~/.bin/conctl u sshd
fi
~/.bin/conctl s sshd
echo "(enter to quit)" ; read PAUSE
