#!/data/data/com.termux/files/usr/bin/sh

printf "Starting cron... "
if pidof crond >/dev/null
then
	echo "already running"
else
	if crond >/dev/null 2>&1
	then
		busybox printf '\e[32mokay\e[0m\n'
	else
		busybox printf '\e[31mERROR!\e[0m\n'
	fi
fi

printf "Starting ssh-agent... "
if pidof ssh-agent >/dev/null
then
	echo "already running"
else
	export SSH_AUTH_SOCK="$HOME/.ssh/S.ssh-agent"
	rm "$SSH_AUTH_SOCK" >/dev/null 2>&1
	if ssh-agent -a "$HOME/.ssh/S.ssh-agent" >/dev/null 2>&1
	then
		busybox printf '\e[32mokay\e[0m\n'
	else
		busybox printf '\e[31mERROR!\e[0m\n'
	fi
fi

printf "Starting gpg-agent... "
if pidof gpg-agent >/dev/null
then
	echo "already running"
else
	export GPG_TTY="$(tty)"
	export GPG_AGENT_INFO="$HOME/.gnupg/S.gpg-agent::1"
	rm "$GPG_AGENT_INFO" >/dev/null 2>&1
	if gpg-agent --daemon --use-standard-socket >/dev/null 2>&1
	then
		busybox printf '\e[32mokay\e[0m\n'
	else
		busybox printf '\e[31mERROR!\e[0m\n'
	fi
fi
